AllCops:
  EnabledByDefault: true
  Exclude:
    - 'bin/*'
  TargetRubyVersion: 2.7

Bundler/GemComment:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true
  NumberOfEmptyLines: [1, 2]

Layout/FirstMethodArgumentLineBreak:
  Enabled: false

Layout/LineLength:
  Max: 100

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Metrics/BlockLength:
  Max: 10

Metrics/MethodLength:
  Max: 15

Metrics/ParameterLists:
  CountKeywordArgs: false

Naming/MethodParameterName:
  AllowedNames: ['as']

Style/AccessModifierDeclarations:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  EnforcedStyle: semantic
  AllowBracesOnProceduralOneLiners: true

Style/ConstantVisibility:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: false

Style/InlineComment:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  IgnoredMethods:
    - import
    - gem
    - p
    - pp
    - puts
    - raise
    - require
    - require_relative
    - source
    - yield
